### PR TITLE
2024 iPad Air intrinsics

### PR DESCRIPTION
**Pull request by mattpetrucci**
Changes include duplicating the intrinsics folder from iPad 13.16 (5th generation 2022 iPad Air) to the new 2024 iPad Air models (11" iPad 14,8 and iPad 14,9; 13" iPad 14,10; iPad 14,11) which have the same rear facing cameras as the 5th generation.

### CODE REVIEW

**Comment by mattpetrucci** [comment]
[OpenCap intrinsics](https://trello.com/c/wSqMZhlD/67-opencap-intrinsics)

**Review by antoinefalisse — APPROVED** [review]
@carmichaelong can you confirm the hardware is the same? I checked that the parameters are good.

**Comment by carmichaelong** [comment]
The most detail I've been able to find so far are Apple's pages for [5th](https://support.apple.com/en-us/111887) and [6th](https://www.apple.com/ipad-air/specs/) gen iPad Airs. Suggests that these are likely the same, but hard to be 100% sure unless there are specs hidden deeper somewhere.

**Comment by antoinefalisse** [comment]
@mattpetrucci and @carmichaelong I think we're good to go here. Let's merge together with https://github.com/stanfordnmbl/opencap-core/pull/199 so that we stop receiving emails haha.

**Comment by mattpetrucci** [comment]
@antoinefalisse I agree. We will also follow up with the people on the forum that have asked about this to see if they can collect some data and we can double check the kinematics are looking okay.

I don't have merging capabilities so go for it!

**Pull request merged**
